version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate code from proto files"
    cmds:
      - buf generate
  dep_update:
    aliases:
      - dep
    desc: "Update deps"
    cmds:
      - buf dep update